@REM Align TheRock build with the ROCm hipSdk stack (MIOpen disabled).

@REM Excludes ORT/EP/ModelBench/MIGraphX/rocMLIR (not in TheRock).

@REM BinSkim / compliance: CFG (/guard:cf) + static MSVC CRT (/MT) where supported.

@REM After changing flags: re-run this script, then expunge/rebuild affected targets.

@REM Example: ninja -C build amd-comgr+expunge hip-clr+expunge && ninja -C build

@REM hipBLASLt Tensile logic keep-set: stage only the kept-stem YAMLs so the
@REM LIBLOGIC_PATH + FILTER=* below trims Tensile (copying alone still builds all).
set "_HBSRC=%~dp0rocm-libraries\projects\hipblaslt\library\src\amd_detail\rocblaslt\src\Tensile\Logic\asm_full"
set "_HBKEEP=%~dp0build\logic-keep\library\src\amd_detail\rocblaslt\src\Tensile\Logic\asm_full"
set "_DP0=%~dp0"
set "_DP0=%_DP0:\=/%"
set "_PY=%_DP0%.venv/Scripts/python.exe"
set "_HBLOGIC=%_DP0%build/logic-keep/library"
if exist "%~dp0build\logic-keep" rmdir /s /q "%~dp0build\logic-keep"
set "_STEMS_115X=Cijk_Ailk_Bljk_HHS_BH_Bias_HAS_SAV_UserArgs Cijk_Alik_Bljk_HHS_BH_Bias_HAS_SAV_UserArgs Cijk_Ailk_Bljk_HSS_BH_Bias_HAS_SAV_UserArgs Cijk_Alik_Bljk_HSS_BH_Bias_HAS_SAV_UserArgs Cijk_Alik_Bljk_HSS_BH_Bias_HAH Cijk_Ailk_Bljk_S_B_Bias_HAS_SAV_UserArgs Cijk_Alik_Bljk_S_B_Bias_HA_S_SAV_UserArgs"
for %%A in (gfx1150 gfx1151 gfx1152 gfx1153) do (
	md "%_HBKEEP%\%%A\GridBased" 2>nul
	for %%S in (%_STEMS_115X%) do if exist "%_HBSRC%\%%A\GridBased\%%A_%%S.yaml" copy /y "%_HBSRC%\%%A\GridBased\%%A_%%S.yaml" "%_HBKEEP%\%%A\GridBased\" >nul
)
set "_STEMS_117X=Cijk_Ailk_Bljk_HHS_BH_Bias_SHB_HA_S_SAB_SCD_SAV_UserArgs Cijk_Alik_Bljk_HHS_BH_Bias_SHB_HA_S_SAB_SCD_SAV_UserArgs Cijk_Ailk_Bljk_HSS_BH_Bias_SHB_HA_S_SAB_SCD_SAV_UserArgs Cijk_Alik_Bljk_HSS_BH_Bias_SHB_HA_S_SAB_SCD_SAV_UserArgs"
for %%A in (gfx1170) do (
	md "%_HBKEEP%\%%A\GridBased" 2>nul
	for %%S in (%_STEMS_117X%) do if exist "%_HBSRC%\%%A\GridBased\%%A_%%S.yaml" copy /y "%_HBSRC%\%%A\GridBased\%%A_%%S.yaml" "%_HBKEEP%\%%A\GridBased\" >nul
)

cmake -B build -GNinja . ^

    -DCMAKE_C_COMPILER_LAUNCHER=sccache ^

	-DCMAKE_CXX_COMPILER_LAUNCHER=sccache ^

	-DPython3_EXECUTABLE=%_PY% ^

	-DPython_EXECUTABLE=%_PY% ^

	-DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON ^

	-DBUILD_TESTING=OFF -DTHEROCK_BUILD_TESTING=OFF ^

	-DTHEROCK_AMDGPU_FAMILIES= ^

	-DTHEROCK_AMDGPU_TARGETS=gfx1150;gfx1151;gfx1152;gfx1153;gfx1170 ^

	-DTHEROCK_DIST_AMDGPU_TARGETS=gfx1150;gfx1151;gfx1152;gfx1153;gfx1170 ^

	-DTHEROCK_TEST_AMDGPU_FAMILIES= ^

	-DTHEROCK_AMDGPU_DIST_BUNDLE_NAME=gfx1150-gfx1151-gfx1152-gfx1153-gfx1170 ^

	-DTHEROCK_TEST_AMDGPU_TARGETS=gfx1150;gfx1151;gfx1152;gfx1153;gfx1170 ^

	-DTHEROCK_ENABLE_OCL_RUNTIME=OFF ^

	-DTHEROCK_ENABLE_COMM_LIBS=OFF ^

	-DTHEROCK_ENABLE_DC_TOOLS=OFF ^

	-DTHEROCK_ENABLE_DEBUG_TOOLS=OFF ^

	-DTHEROCK_ENABLE_STORAGE_LIBS=OFF ^

	-DTHEROCK_ENABLE_MEDIA_LIBS=OFF ^

	-DTHEROCK_ENABLE_EMULATION=OFF ^

	-DTHEROCK_ENABLE_ROCPROFSYS=OFF ^

	-DTHEROCK_ENABLE_HIPIFY=OFF ^

	-DTHEROCK_ENABLE_CORE_HIPINFO=OFF ^

	-DTHEROCK_ENABLE_CORE_HIPTESTS=OFF ^

	-DTHEROCK_ENABLE_MIOPEN=OFF ^

	-DTHEROCK_ENABLE_MIOPEN_PLUGIN=OFF ^

	-DTHEROCK_ENABLE_HIPDNN=OFF ^

	-DTHEROCK_ENABLE_HIPDNN_INTEGRATION_TESTS=OFF ^

	-DTHEROCK_ENABLE_MIOPENPROVIDER=OFF ^

	-DTHEROCK_ENABLE_HIPBLASLTPROVIDER=OFF ^

	-DTHEROCK_ENABLE_HIPDNN_SAMPLES=OFF ^

	-DTHEROCK_ENABLE_HIPKERNELPROVIDER=OFF ^

	-DTHEROCK_ENABLE_ROCWMMA=OFF ^

	-DTHEROCK_ENABLE_PRIM=OFF ^

	-DTHEROCK_ENABLE_LIBHIPCXX=OFF ^

	-DTHEROCK_ENABLE_ROCALUTION=OFF ^

	-DTHEROCK_ENABLE_FFT=OFF ^

	-DTHEROCK_ENABLE_SPARSE=OFF ^

	-DTHEROCK_ENABLE_SOLVER=OFF ^

	-DTHEROCK_ENABLE_FFTW3=OFF ^

	-DTHEROCK_ENABLE_COMPOSABLE_KERNEL=OFF ^

	-Damd-llvm_CMAKE_ARGS="-DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON;-DLLVM_PARALLEL_LINK_JOBS=2;-DLLVM_USE_BINSKIM_COMPLIANT_COMPILE_FLAGS=ON;-DLLVM_USE_MSVC_STATIC_RUNTIME=ON;-DROCM_DEVICE_LIBS_USE_BINSKIM_COMPLIANT_COMPILE_FLAGS=ON;-DROCM_DEVICE_LIBS_USE_MSVC_STATIC_RUNTIME=ON;-DZLIB_USE_STATIC_LIBS=ON" ^

	-Damd-comgr_CMAKE_ARGS="-DCOMGR_DLL_NAME=amd_comgr0714.dll;-DCOMGR_DISABLE_SPIRV=OFF;-DCOMGR_EMBED_LIBCXX_HEADERS=ON;-DCOMGR_USE_INCBIN=OFF;-DCOMGR_USE_BINSKIM_COMPLIANT_COMPILE_FLAGS=ON;-DCOMGR_USE_MSVC_STATIC_RUNTIME=ON;-DZLIB_USE_STATIC_LIBS=ON" ^

	-Dhip-clr_CMAKE_ARGS="-D__HIP_USE_BINSKIM_COMPLIANT_COMPILE_FLAGS=ON;-DZLIB_USE_STATIC_LIBS=ON;-DROCM_KPACK_ENABLED=OFF;-DCOMGR_DLL_NAME=amd_comgr0714.dll" ^

	-Drocm-kpack_CMAKE_ARGS="-DBUILD_SHARED_LIBS=OFF" ^

	-DrocRAND_CMAKE_ARGS="-DROCRAND_USE_BINSKIM_COMPLIANT_COMPILE_FLAGS=ON;-DROCRAND_USE_MSVC_STATIC_RUNTIME=ON" ^

	-DhipBLASLt_CMAKE_ARGS="-DCMAKE_POLICY_VERSION_MINIMUM=3.10;-DZLIB_USE_STATIC_LIBS=ON;-DHIPBLASLT_BUILD_TESTING=OFF;-DHIPBLASLT_ENABLE_CLIENT=OFF;-DHIPBLASLT_ENABLE_AMD_SMI=OFF;-DHIPBLASLT_ENABLE_FETCH=ON;-DTENSILELITE_BUILD_TESTING=OFF;-DHIPBLASLT_USE_BINSKIM_COMPLIANT_COMPILE_FLAGS=ON;-DHIPBLASLT_USE_MSVC_STATIC_RUNTIME=ON;-DPython3_EXECUTABLE=%_PY%;-DPython_EXECUTABLE=%_PY%;-DHIPBLASLT_LIBLOGIC_PATH=%_HBLOGIC%;-DTENSILELITE_LOGIC_FILTER=*" ^

	-DrocBLAS_CMAKE_ARGS="-DROCBLAS_USE_BINSKIM_COMPLIANT_COMPILE_FLAGS=ON;-DROCBLAS_USE_MSVC_STATIC_RUNTIME=OFF" ^

	-DhipBLAS_CMAKE_ARGS="-DHIPBLAS_USE_BINSKIM_COMPLIANT_COMPILE_FLAGS=ON;-DHIPBLAS_USE_MSVC_STATIC_RUNTIME=ON" ^

	-Dcomposable_kernel_CMAKE_ARGS="-DCMAKE_POLICY_VERSION_MINIMUM=3.10;-DBUILD_CK_EXAMPLES=OFF;-DBUILD_CK_TUTORIALS=OFF;-DBUILD_DEV=OFF;-DCK_USE_BINSKIM_COMPLIANT_COMPILE_FLAGS=ON;-DCK_USE_MSVC_STATIC_RUNTIME=ON;-DENABLE_CLANG_CPP_CHECKS=OFF" ^

	-Dtherock-sqlite3_CMAKE_ARGS="-DROCM_SYSDEPS_USE_MSVC_STATIC_RUNTIME=ON" ^
	-Dtherock-bzip2_CMAKE_ARGS="-DROCM_SYSDEPS_USE_MSVC_STATIC_RUNTIME=ON"

cmake --build build --target dist
